--Game States
GAME_STATE_MAIN_MENU = "MAIN MENU"
GAME_STATE_PLAYING = "PLAYING"
GAME_STATE_DEAD = "DEAD"
GAME_STATE_PAUSE = "PAUSE"
GAME_STATE_CREDITS = "CREDITS"

--Collider Types
COLLIDER_TYPE_PLAYER="Player"
COLLIDER_TYPE_PLAYER_GROUND_DETECTION="Player-GroundDetection"
COLLIDER_TYPE_CHECKPOINT="Checkpoint"
COLLIDER_TYPE_SPIKE="Spike"
COLLIDER_TYPE_WALL="Wall"
COLLIDER_TYPE_WARP="Warp"
COLLIDER_TYPE_DOOR="Door"

INVINCIBILITY_FRAMES=60

DISPLAY_COLLIDERS=true

--Height of the HUD in pixels
HUD_HEIGHT=40

--Size of tiles in pixels
BASE_TILE_SIZE=16

GAME_WIDTH=640
GAME_HEIGHT=360

--Object Types
OBJECT_TYPE_ITEM="ITEM"
OBJECT_TYPE_WARP="WARP"
OBJECT_TYPE_DOOR="DOOR"
OBJECT_TYPE_TERRAIN="TERRAIN"
OBJECT_TYPE_SPIKE="SPIKE"
OBJECT_TYPE_CREDIT="CREDIT"