--Game States
GAME_STATE_MAIN_MENU = "MAIN MENU"
GAME_STATE_PLAYING = "PLAYING"
GAME_STATE_DEAD = "DEAD"
GAME_STATE_PAUSE = "PAUSE"

--Collider Types
COLLIDER_TYPE_PLAYER="Player"
COLLIDER_TYPE_PLAYER_GROUND_DETECTION="Player-GroundDetection"
COLLIDER_TYPE_CHECKPOINT="Checkpoint"
COLLIDER_TYPE_SPIKE="Spike"
COLLIDER_TYPE_WALL="Wall"
COLLIDER_TYPE_WARP="Warp"

INVINCIBILITY_FRAMES=60

DISPLAY_COLLIDERS=true

--Height of the HUD in pixels
HUD_HEIGHT=40

--Size of tiles in pixels
TILE_SIZE=16